### ISSUE TITLE
Does onnxruntime-extensions support inference with only one node such as ‘conv’ or ‘clip’ in the onnx model? 

### ISSUE THREAD

**Issue by moonjiaoer** [microsoft/onnxruntime-extensions#103]
I try to execute one node at a time, this node could be ‘conv’ or ‘clip’, etc. for example. And this node not necessarily be the input node of the model. To be more concrete, I put an example model here in Fig 1. Instead of running the whole model (set the input data for the node ‘input’, and expect to get the result of the node ‘clip’), I want to execute the ‘clip’ node (set the input data for the node ‘clip’, and expect to get the result of the node ‘clip’).
![1238456898](https://user-images.githubusercontent.com/25788679/120573690-97509300-c450-11eb-8bf5-26fb53fb6a00.jpg)
Fig.1

I tried to achieve this by change the parameters of the function ‘run’, such as: 
res = sess.run([output_name], {'clip': x})
But get an error: onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Invalid Feed Input Name:clip. 

Seems like this parameter is used for the model with multiple input node, it doesn’t work for the case that you want to choose which node you really want to INPUT the data other than the input node.

Does anyone know how to achieve this? Or if the ORT has such a function?

**Comment by Toudsour** [comment]
Hi, ONNX model is a workflow and could only be executed from definite input (in your example, it's `input.1`） to the output, so you cannot select an arbitrary node as input. To achieve your goal, you can modify the model with [onnx helper](https://github.com/onnx/onnx/blob/master/docs/PythonAPIOverview.md). 

BTW: you can put your issue on [onnx](https://github.com/onnx/onnx) and there are more people answer your question.

**Comment by moonjiaoer** [comment]
Thank you. What I am puzzled is that there is a sentence--"Support Python per operator debugging, checking hook_model_op in onnxruntime_extensions Python package" on the project homepage . Its meaning is consistent with my goal. But I did not find the way to execute the individual operator. Can you help me answer it?

**Comment by Toudsour** [comment]
Maybe @wenbingl  can help answer the question.

**Comment by wenbingl** [comment]
@moonjiaoer , your requirement can be easily satisfied as the following way 

new_model = build_model_from_ops(original_model, [op_names])
node_func = PyOrtFunction.from_model(new_model)
outputs = node_func(inputs)

build_model_from_ops hasn't been exposed to be a API, I may add it later.


While hook_model_op tries to solve a challenge problem, on executing on a big ONNX-graph, how can we inspect the inputs/outputs of a certain node on the fly.
