### ISSUE TITLE
building static lib error: undefined reference to `USER_ERROR__$ nconsistent_build_configuration__see_dlib_faq_1_'

### ISSUE THREAD

**Issue by raymon-tian** [microsoft/onnxruntime-extensions#112]
following  the [script](https://github.com/microsoft/onnxruntime-extensions/blob/main/ci_build/onnxruntime_integration/build_with_onnxruntime.sh), I would like to build the project as a static library and link it into ONNXRuntime, but it failed.

log is here:

```
[ 75%] Linking CXX executable onnxruntime_perf_test
external/onnxruntime-extensions/libocos_operators.a(math.cc.o): In function `__static_initializati$
n_and_destruction_0(int, int)':
/home/xxx/onnxruntime_customops_integration/build/Debug/_deps/dl$
b-src/dlib/matrix/../threads/../test_for_odr_violations.h:24: undefined reference to `USER_ERROR__$
nconsistent_build_configuration__see_dlib_faq_1_'
/home/xxx/onnxruntime_customops_integration/build/Debug/_deps/dl$b-src/dlib/matrix/../threads/../test_for_odr_violations.h:42: undefined reference to `USER_ERROR__$nconsistent_build_configuration__see_dlib_faq_2'
collect2: error: ld returned 1 exit status
CMakeFiles/onnxruntime_perf_test.dir/build.make:214: recipe for target 'onnxruntime_perf_test' fai$ed
make[2]: *** [onnxruntime_perf_test] Error 1
CMakeFiles/Makefile2:448: recipe for target 'CMakeFiles/onnxruntime_perf_test.dir/all' failed
make[1]: *** [CMakeFiles/onnxruntime_perf_test.dir/all] Error 2
Makefile:181: recipe for target 'all' failed
make: *** [all] Error 2
```
toolchain versions:
g++ : 8.4.0
gcc: 8.4.0
cmake: 3.19.1
system: ubuntu 18.04.

In addition, I set ```OCOS_ENABLE_CTEST``` true in `CMakeLists.txt`, but the failure log says "The ctest needs the prebuilt onnxruntime libraries directory, please specify it by ONNXRUNTIME_LIB_DIR".

How to set ```ONNXRUNTIME_LIB_DIR```?  thanks.

**Comment by raymon-tian** [comment]
the second problem has been solved.

**Comment by wenbingl** [comment]
@raymon-tian , you can add an argument OCOS_ENABLE_MATH=OFF to skip this error.

**Comment by wenbingl** [comment]
@Zuwei-Zhao, you just updated the patch recently, did you encounter this issue as well?

**Comment by raymon-tian** [comment]
> @raymon-tian , you can add an argument OCOS_ENABLE_MATH=OFF to skip this error.

thanks, it works, but a new failure  was got: 
```
[ 96%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/xxx/onnxruntime_customops_integration/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc.
o
/home/xxx/onnxruntime_customops_integration/onnxruntime/onnxrunti
me/test/shared_lib/test_inference.cc: In member function ‘virtual void CApiTest_test_enable_ort_cus
tomops_negpos_Test::TestBody()’:
/home/xxx/onnxruntime_customops_integration/onnxruntime/onnxrunti
me/test/shared_lib/test_inference.cc:274:33: error: ‘make_unique’ is not a member of ‘onnxruntime’
   auto allocator = onnxruntime::make_unique<MockedOrtAllocator>();
                                 ^~~~~~~~~~~

```

if I compile standalone ORT following [1], it works well.

[1]. https://www.onnxruntime.ai/docs/how-to/build/inferencing.html#linux

**Comment by raymon-tian** [comment]
After I set 
```
  // auto allocator = onnxruntime::make_unique<MockedOrtAllocator>();
  auto allocator = std::make_unique<MockedOrtAllocator>();
```
in the onnxruntime_customops_integration/onnxruntime/onnxruntime/test/shared_lib/test_inference.cc, compiling works well, but some testcases aren't passed.

**Comment by snnn** [comment]
I removed onnxruntime::make_unique
