### ISSUE TITLE
beginner question about gpt2bs.py

### ISSUE THREAD

**Issue by gyin-ai** [microsoft/onnxruntime-extensions#115]
1. can I ask why we need the `onnxruntime-extensions` to run this python file? If we only want to run `gpt2_full.onnx` without the tokenizer part, does it still need `onnxruntime-extensions` to build into onnxruntime (triton backend)? @wenbingl 

2. Can it early stop at eos_token prediction? 

2. This is so exciting for gpt2 auto-regressive decoding, which is the unique inference optimized implementation with fusion, past state and int8 quantization for CPU now. Is it possible we have the benchmark on CPU or even GPU documented? (For GPU, it can compare with fastertransformer and lightseq)

**Comment by wenbingl** [comment]
1. No, no need of onnxruntime-extension if there is no tokenizer required.
2. Yes
3. This is the first time to put all algorithms into a single ONNX model, and the inference optimization and benchmarking is ongoing by ONNXRuntime team.

**Comment by gyin-ai** [comment]
@wenbingl it looks like it couldn't handle dynamic input length which is not the size of the dummy tracing input. The one step beamsearchhelper could do it. Any idea how we can solve it?

**Comment by wenbingl** [comment]
The dynamic inputs can be fixed in this way: https://github.com/microsoft/onnxruntime-extensions/pull/118/commits/59795c3a19d09edd6e44a34c931ffc25a50802bd.

both  gpt2_e2e and gpt2_bs are some tutorial script to demo the usage of onnxprocess. And they are depending on the different core model, which makes them have some difference. Like eos implementation are different.

and gpt2_e2e is a greedy search, could be a special case of beam search on beam-width == 1

Overall gp2_e2e hasn't been updated for a while,  the gp2bs is the latest one.

**Comment by gyin-ai** [comment]
@wenbingl when I tried to use int8 quantization as the core_model, it seemed not working and would crash.
https://github.com/microsoft/onnxruntime/blob/a9a2394fa5b7ab0f8b55b2ecfeefb91967eedff9/onnxruntime/python/tools/transformers/notebooks/Inference_GPT2_with_OnnxRuntime_on_CPU.ipynb
```
optimized_fp32_model_path = "gpt2_fp32.onnx"
quantized_int8_model_path = "gpt2_int8.onnx"
Gpt2Helper.optimize_onnx("gpt2.onnx", optimized_fp32_model_path, False, model.config.num_attention_heads, model.config.hidden_size)
QuantizeHelper.quantize_onnx_model(optimized_fp32_model_path, quantized_int8_model_path)
```

**Comment by wenbingl** [comment]
there is a bug ORT 1.8 which was fixed

> @wenbingl when I tried to use int8 quantization as the core_model, it seemed not working and would crash.
> https://github.com/microsoft/onnxruntime/blob/a9a2394fa5b7ab0f8b55b2ecfeefb91967eedff9/onnxruntime/python/tools/transformers/notebooks/Inference_GPT2_with_OnnxRuntime_on_CPU.ipynb
> 
> ```
> optimized_fp32_model_path = "gpt2_fp32.onnx"
> quantized_int8_model_path = "gpt2_int8.onnx"
> Gpt2Helper.optimize_onnx("gpt2.onnx", optimized_fp32_model_path, False, model.config.num_attention_heads, model.config.hidden_size)
> QuantizeHelper.quantize_onnx_model(optimized_fp32_model_path, quantized_int8_model_path)
> ```

there was a bug in ORT 1.8 which is fixed in the master branch, you can try the nightly build, build it by yourself or wait for the patch release, which will be soon.
