### ISSUE TITLE
How to set dynamic input type?

### ISSUE THREAD

**Issue by lovepan1** [microsoft/onnxruntime-extensions#120]
hello, i want to set dynamic input type,  for example:

ONNXTensorElementDataType CustomOpVectorToString::GetInputType(size_t /*index*/) const {
  return ONNX_TENSOR_ELEMENT_DATA_TYPE_INT64;
};
I only have one input parameter, but the input type may be int64 or float32， how can i modify the code， thank U。

**Comment by wenbingl** [comment]
I don't know whether there already is a official solution support in ONNXRuntime yet, @hariharans29, do you have an answer?

@lovepan1 , but there is a simple way to do this that you can create two kernels with the different names for the type respectively.

**Comment by hariharans29** [comment]
ONNX Runtime supports dynamic type inputs/outputs. - https://github.com/microsoft/onnxruntime/issues/6469

**Comment by lovepan1** [comment]
thanks a lot!
