### ISSUE TITLE
I want to know the role of the gpt_onnx files in your codes.

### ISSUE THREAD

**Issue by shp776** [microsoft/onnxruntime-extensions#124]
https://github.com/microsoft/onnxruntime-extensions/blob/main/tutorials/gpt2_e2e.py

gpt2_core_model_path = './gpt2.onnx'
gpt2_encoder_model_path = './gpt2_tok.onnx'
gpt2_decoder_model_path = './gpt2_dec.onnx'
gpt2_full_model_path = './gpt2_full.onnx'

I can't judge exactly the roles of the onnx files above in this link. Therefore, I would like to ask you a question as follows.

1. What is the difference between core_model (gpt2.onnx) and full_model (gpt2_full.onnx)?
I wonder what model plays the role of converting input_tensor into output_tensor(input_tensor -> output_tensor) 

2. I am going to do gpt2 text generation using C/C++ API. It seems that encoder_model (gpt2_tok.onnx) converts text into input_tensor(text -> input_tensor) and decoder_model (gpt2_dec.onnx) converts output_tensor into text(output_tensor -> text). If I call 3 onnx files(tok.onnx, dec.onnx, and the onnx file which converts input_tensor into output_tensor) and then do ORT_SESSION_RUN, is it right that I can get the results I want?

3. gpt2_bs.Py seems to contain text_generation_code using the beam search algorithm. What is the exact role difference between gpt2_e2e.py and gpt2_bs.py?

I`m novice of this area. It would be very helpful to me if you explained above questions in detail.

Thank you.

**Comment by wenbingl** [comment]
@shp776, the core_model is the one directly exported from pytorch model by some scripts.
considering a the greedy algorithm in gpt2_e2e.py is the simplified version of beam search, let's start with gp2bs. 

The goal of these script here is to create all-in-one model -0 gpt2_full.onnx, which will only call session.run to get the final result.
