### ISSUE TITLE
project building error

### ISSUE THREAD

**Issue by YuxinWang6** [microsoft/onnxruntime-extensions#130]
I got errors when doing 'python setup.py install'

onnxruntime 1.8.0
python 3.7.3
cmake 3.21.1
system: Ubuntu 16.04

/usr/include/c++/5/bits/stl_vector.h:253:7: note:   candidate expects 0 arguments, 1 provided
CMakeFiles/ocos_operators.dir/build.make:355: recipe for target 'CMakeFiles/ocos_operators.dir/operators/math/math.cc.o' failed
gmake[2]: *** [CMakeFiles/ocos_operators.dir/operators/math/math.cc.o] Error 1
CMakeFiles/ocos_operators.dir/build.make:369: recipe for target 'CMakeFiles/ocos_operators.dir/operators/tokenizer/gpt2_tokenizer.cc.o' failed
gmake[2]: *** [CMakeFiles/ocos_operators.dir/operators/tokenizer/gpt2_tokenizer.cc.o] Error 1
CMakeFiles/Makefile2:379: recipe for target 'CMakeFiles/ocos_operators.dir/all' failed
gmake[1]: *** [CMakeFiles/ocos_operators.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
gmake: *** [all] Error 2
error: command 'cmake' failed with exit status 2

log is attached
[LOG.log](https://github.com/microsoft/onnxruntime-extensions/files/6997980/LOG.log)

**Comment by wenbingl** [comment]
can you paste your gcc version as well?
onnxruntime-extension needs to be compiled by gcc-8 and above to support c++-17 feature.

**Comment by YuxinWang6** [comment]
I used gcc 5.5, Thanks!
