### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

### ISSUE THREAD

**Issue by captain81** [microsoft/onnxruntime-extensions#141]
Hi,
I’m trying to convert a pytorch model to onnx, but the conversion gives the following error:

RuntimeError: ONNX export failed: Couldn’t export Python operator qfn

The definition for qfn is:

class qfn(torch.autograd.Function):
@staticmethod
def forward(ctx, input, k):
n = float(2**k - 1)
out = torch.round(input * n) / n
return out

@staticmethod
def backward(ctx, grad_output):
    grad_input = grad_output.clone()
    return grad_input, None

**Comment by wenbingl** [comment]
check the following example:

# export the model
import torch

class qfn(torch.autograd.Function):
    @staticmethod
    def symbolic(g, input, k):
        return g.op('ai.onnx.contrib::qfn', input, k)

    @staticmethod
    def forward(ctx, input, k):
        n = (2**k - 1).type(torch.float)
        out = torch.round(input * n) / n
        return out

    @staticmethod
    def backward(ctx, grad_output):
        grad_input = grad_output.clone()
        return grad_input, None


class TestModule(torch.nn.Module):
    def forward(self, input, k):
        return qfn.apply(input, k)


torch.onnx.export(TestModule(), 
    (torch.randn(3, 3), torch.tensor(10)),
    'test_qfn.onnx')





# Test the exported model with onnxruntime-extensions.
import numpy as np
import onnxruntime_extensions as _ext

from onnxruntime_extensions import PyOp, onnx_op

@onnx_op(op_type='qfn', inputs=[PyOp.dt_float, PyOp.dt_int64])
def qfn(input, k):
    n = float(2**k - 1)
    out = np.round(input * n) / n
    return out

inference_func = _ext.PyOrtFunction.from_model('test_qfn.onnx')
print(inference_func(np.random.randn(3, 3).astype(np.float32), 10))

**Comment by Yaodada12** [comment]
> check the following example:
> 
> ```
> # export the model
> import torch
> 
> class qfn(torch.autograd.Function):
>     @staticmethod
>     def symbolic(g, input, k):
>         return g.op('ai.onnx.contrib::qfn', input, k)
> 
>     @staticmethod
>     def forward(ctx, input, k):
>         n = (2**k - 1).type(torch.float)
>         out = torch.round(input * n) / n
>         return out
> 
>     @staticmethod
>     def backward(ctx, grad_output):
>         grad_input = grad_output.clone()
>         return grad_input, None
> 
> 
> class TestModule(torch.nn.Module):
>     def forward(self, input, k):
>         return qfn.apply(input, k)
> 
> 
> torch.onnx.export(TestModule(), 
>     (torch.randn(3, 3), torch.tensor(10)),
>     'test_qfn.onnx')
> 
> 
> # Test the exported model with onnxruntime-extensions.
> import numpy as np
> import onnxruntime_extensions as _ext
> 
> from onnxruntime_extensions import PyOp, onnx_op
> 
> @onnx_op(op_type='qfn', inputs=[PyOp.dt_float, PyOp.dt_int64])
> def qfn(input, k):
>     n = float(2**k - 1)
>     out = np.round(input * n) / n
>     return out
> 
> inference_func = _ext.PyOrtFunction.from_model('test_qfn.onnx')
> print(inference_func(np.random.randn(3, 3).astype(np.float32), 10))
> ```

Hi，can you give me some help？I got some error when i register DCNV2 to onnxruntime。
===============================DCNv2 define code=============================
class ModulatedDeformConvFunction(Function):

    @staticmethod
    def symbolic(g, input, offset, mask, weight, bias=None, stride=1, padding=0, dilation=1, groups=1,
                 deformable_groups=1):
        return g.op('ai.onnx.contrib::ModulatedDeformConvFunction', input, offset, mask, weight, bias_f=bias,
                    stride_i=stride, padding_i=padding, dilation_i=dilation, groups_i=groups,
                    deformable_groups_i=deformable_groups)

    @staticmethod
    def forward(ctx,
                input,
                offset,
                mask,
                weight,
                bias=None,
                stride=1,
                padding=0,
                dilation=1,
                groups=1,
                deformable_groups=1):
        ctx.stride = stride
        ctx.padding = padding
        ctx.dilation = dilation
        ctx.groups = groups
        ctx.deformable_groups = deformable_groups
        ctx.with_bias = bias is not None
        if not ctx.with_bias:
            bias = input.new_empty(1)  # fake tensor
        if not input.is_cuda:
            raise NotImplementedError
        if weight.requires_grad or mask.requires_grad or offset.requires_grad \
                or input.requires_grad:
            ctx.save_for_backward(input, offset, mask, weight, bias)
        output = input.new_empty(
            ModulatedDeformConvFunction._infer_shape(ctx, input, weight))
        ctx._bufs = [input.new_empty(0), input.new_empty(0)]
        deform_conv_cuda.modulated_deform_conv_cuda_forward(
            input, weight, bias, ctx._bufs[0], offset, mask, output,
            ctx._bufs[1], weight.shape[2], weight.shape[3], ctx.stride,
            ctx.stride, ctx.padding, ctx.padding, ctx.dilation, ctx.dilation,
            ctx.groups, ctx.deformable_groups, ctx.with_bias)
        return output

    @staticmethod
    def backward(ctx, grad_output):
        if not grad_output.is_cuda:
            raise NotImplementedError
        input, offset, mask, weight, bias = ctx.saved_tensors
        grad_input = torch.zeros_like(input)
        grad_offset = torch.zeros_like(offset)
        grad_mask = torch.zeros_like(mask)
        grad_weight = torch.zeros_like(weight)
        grad_bias = torch.zeros_like(bias)
        deform_conv_cuda.modulated_deform_conv_cuda_backward(
            input, weight, bias, ctx._bufs[0], offset, mask, ctx._bufs[1],
            grad_input, grad_weight, grad_bias, grad_offset, grad_mask,
            grad_output, weight.shape[2], weight.shape[3], ctx.stride,
            ctx.stride, ctx.padding, ctx.padding, ctx.dilation, ctx.dilation,
            ctx.groups, ctx.deformable_groups, ctx.with_bias)
        if not ctx.with_bias:
            grad_bias = None

        return (grad_input, grad_offset, grad_mask, grad_weight, grad_bias,
                None, None, None, None, None)

    @staticmethod
    def _infer_shape(ctx, input, weight):
        n = input.size(0)
        channels_out = weight.size(0)
        height, width = input.shape[2:4]
        kernel_h, kernel_w = weight.shape[2:4]
        height_out = (height + 2 * ctx.padding -
                      (ctx.dilation * (kernel_h - 1) + 1)) // ctx.stride + 1
        width_out = (width + 2 * ctx.padding -
                     (ctx.dilation * (kernel_w - 1) + 1)) // ctx.stride + 1
        return n, channels_out, height_out, width_out
modulated_deform_conv = ModulatedDeformConvFunction.apply
==========================onnxruntime infer code========================
import onnxruntime as ort
from onnxruntime_extensions import get_library_path, PyCustomOpDef, onnx_op
from assets.ops.dcn import deform_conv_cuda

def _infer_shape(input, weight, padding, stride, dilation):
    n = input.size(0)
    channels_out = weight.size(0)
    height, width = input.shape[2:4]
    kernel_h, kernel_w = weight.shape[2:4]
    height_out = (height + 2 * padding -
                  (dilation * (kernel_h - 1) + 1)) // stride + 1
    width_out = (width + 2 * padding -
                 (dilation * (kernel_w - 1) + 1)) // stride + 1
    return n, channels_out, height_out, width_out


@onnx_op(op_type='ModulatedDeformConvFunction', domain='ai.onnx.contrib',
         inputs=[PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float, PyCustomOpDef.dt_float])
def ModulatedDeformConvFunction(input, offset, mask, weight, bias=None,
                                stride=1, padding=0, dilation=1, groups=1, deformable_groups=1):
    print("input:", input)
    print("offset:", offset)
    print("mask:", mask)
    print("weight:", weight)
    if not bias:
        bias = torch.from_numpy(input).new_empty(1)  # fake tensor
    output = torch.from_numpy(input).new_empty(_infer_shape(input, weight, padding, stride, dilation))

    deform_conv_cuda.modulated_deform_conv_cuda_forward(
        input, weight, bias, torch.from_numpy(input).new_empty(0), offset, mask, output,
        torch.from_numpy(input).new_empty(0), weight.shape[2], weight.shape[3], stride,
        stride, padding, padding, dilation, dilation,
        groups, deformable_groups, bias)
    return output  # this works, I can get output, but when I run session.run() get error.

so = ort.SessionOptions()
so.register_custom_ops_library(get_library_path())
providers = ['CUDAExecutionProvider', 'CPUExecutionProvider']

sess = ort.InferenceSession("checkpoints/db_resnet50.onnx", so, providers=providers)
img = np.ones([1, 3, 640, 640])
pred = session.run([session.get_outputs()[0].name], {session.get_inputs()[0].name: img})[0]
===============================error================================
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'Add_36' Status Message: D:\a\_work\1\s\onnxruntime\core/providers/cpu/math/element_wise_ops.h:523 onnxruntime::BroadcastIterator::Append axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 116 by 230

**Comment by wenbingl** [comment]
close the issue as it is stale
