### ISSUE TITLE
Runtime exception for operator StringRegexSplitWithOffsets in v0.4.0

### ISSUE THREAD

**Issue by sj120698** [microsoft/onnxruntime-extensions#163]
I converted tensorflow's pre-processing model for BERT i.e. bert_en_uncased_preprocess v3 (https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3) into ONNX model using tf2onnx command - 

`python -m tf2onnx.convert --saved-model bert_en_uncased_preprocess_3 --output model.onnx --opset 13 --extra_opset ai.onnx.contrib:1 --custom-ops CaseFoldUTF8:ai.onnx.contrib,NormalizeUTF8:ai.onnx.contrib`

After conversion, I defined the CaseFoldUTF8 and NormalizeUTF8 ops in python as - 

```
import numpy as np
from onnxruntime_extensions import onnx_op, PyCustomOpDef
import string

@onnx_op(op_type="CaseFoldUTF8",
         inputs=[PyCustomOpDef.dt_string],
         outputs=[PyCustomOpDef.dt_string])
def casefold(x):            # convert to lowercase
    temp = []
    temp.append(x[0].lower()) 
    return np.array(temp)

@onnx_op(op_type="NormalizeUTF8",
         inputs=[PyCustomOpDef.dt_string],
         outputs=[PyCustomOpDef.dt_string])
def normalize(x):          # remove punctuations
    temp = []
    temp.append(x[0].translate(str.maketrans('', '', string.punctuation))) 
    return np.array(temp)

```

After this, I inferred the ONNX model using the below code - 

```
import onnxruntime as ort
from onnxruntime_extensions import get_library_path

so = ort.SessionOptions()
so.register_custom_ops_library(get_library_path())

sess = ort.InferenceSession("model.onnx",so)
input_name = [node.name for node in sess.get_inputs()]
output_name = [node.name for node in sess.get_outputs()]

tensor1 = np.array(['The movie was great!'])
result = sess.run(output_name, {input_name[0]: tensor1})
```

`sess.run` used to be successful with  onnxruntime-extensions v0.3.1, where as it is now returning the following error with v0.4.0 - 

```
RuntimeException                          Traceback (most recent call last)
<ipython-input-3-f1ba762f7c85> in <module>
      3 
      4 tensor1 = np.array(['The movie was terrible...'])
----> 5 result = sess.run(output_name, {input_name[0]: tensor1})

c:\users\shubham.j\appdata\local\programs\python\python38\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py in run(self, output_names, input_feed, run_options)
    186             output_names = [output.name for output in self._outputs_meta]
    187         try:
--> 188             return self._sess.run(output_names, input_feed, run_options)
    189         except C.EPFail as err:
    190             if self._enable_fallback:

RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running StringRegexSplitWithOffsets node. Name:'StatefulPartitionedCall/model_1/preprocessing/StatefulPartitionedCall/StatefulPartitionedCall/StatefulPartitionedCall/bert_tokenizer/StatefulPartitionedCall/RegexSplitWithOffsets' Status Message: offsets buffer is not equal to tensor size

```
Please let me know how this could be resolved.

**Comment by wenbingl** [comment]
Before we are taking a looking at this issue, can you share what the ONNXRuntime version is?

**Comment by sj120698** [comment]
@wenbingl  I am using onnxruntime v1.7.0 and onnx v1.10.1

**Comment by TomWildenhain-Microsoft** [comment]
I'm having the same issue with `onnxruntime-extensions==0.4.0` but not `onnxruntime-extensions==0.3.1` in tf2onnx unit tests.

**Comment by wenbingl** [comment]
interesting, I check the file history, we didn't do any substantive change on this operator.
I will try to repro this bug with the real model converted from TF, if any of you have one, can you share with me?

**Comment by sj120698** [comment]
@wenbingl, the original TF model can be downloaded from https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3 and can be converted into ONNX model using tf2onnx command -

`python -m tf2onnx.convert --saved-model bert_en_uncased_preprocess_3 --output model.onnx --opset 13 --extra_opset ai.onnx.contrib:1 --custom-ops CaseFoldUTF8:ai.onnx.contrib,NormalizeUTF8:ai.onnx.contrib`

You can also refer this issue's description for more clarity or also let me know in case of any other doubts.

**Comment by wenbingl** [comment]
@sj120698 I made patch release 0.4.2 for fix the issue, please upgrade your pip package and have a try.
