### ISSUE TITLE
Error when running gpt2bs.py _beam_search 

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime-extensions#170]
[ outputs = func_one_step(*states[1:])](https://github.com/microsoft/onnxruntime-extensions/blob/70aa18e14ec7e8cca317c8ae829de799da92de73/tutorials/gpt2bs.py#L132)

 [E:onnxruntime:, sequential_executor.cc:346 
` Message=[ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Equal node. Name:'Equal_2554' Status Message: D:\a\_work\1\s\onnxruntime\core\framework\op_kernel.cc:78 onnxruntime::OpKernelContext::OutputMLValue status.IsOK() was false. Shape mismatch attempting to re-use buffer. {1,1} != {1,4}. Validate usage of dim_value (values should be > 0) and dim_param (all values with the same string should equate to the same size) in shapes in the model.`

### environment
onnx                   1.9.0
onnxconverter-common   1.8.1
onnxruntime            1.9.0
onnxruntime-extensions 0.4.2
onnxruntime-gpu        1.9.0
onnxruntime-tools      1.7.0
transformers           4.11.3
Windows 11

Anyone with similar error?

Suggestion what to do next?

**Comment by vastlik** [comment]
I have the same issue, were you able to resolve it?

**Comment by GeorgeS2019** [comment]
@wenbingl   do allocate some time to address this issue, it seems I am not the only one
@vastlik  thx for feedback, keep doing that, this is an important extension framework. The team needs timely feedback to navigate throught the challenges.

**Comment by GeorgeS2019** [comment]
@natke  has this GPT2 issue been addressed?

**Comment by wenbingl** [comment]
@GeorgeS2019 , onnxruntime itself now support this operator now, so we stopped our efforts, 
check here for more details: https://github.com/microsoft/onnxruntime/blob/ad9d2e2e891714e0911ccc3fa8b70f42025b4d56/docs/ContribOperators.md#commicrosoftbeamsearch

**Comment by GeorgeS2019** [comment]
Here is the [notebook ](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/python/tools/transformers/notebooks/Inference_GPT2-OneStepSearch_OnnxRuntime_CPU.ipynb)for this
