### ISSUE TITLE
[Node has input size * not in range] multiple input operator problem

### ISSUE THREAD

**Issue by nkzyj** [microsoft/onnxruntime-extensions#171]
I tried customize a 2-input operator add2, the operator was exported from a .cpp file. Then I performed the code below to register the operator in onnx, export a small model based on the operator, register the operator in onnxruntime. Add  run the model.  
Software Configuration:
torch: 1.9.1+cu111
onnx: 1.10.1
onnxruntime: 1.9.0
onnxruntime_extensions: 0.4.2
```
import onnx
import numpy as np
import io
import torch
print(onnx.__version__)
shared_library = "add2/build/libadd2.so"
torch.ops.load_library(shared_library)
class pool(torch.nn.Module):
    def __init__(self) -> None:
        super().__init__()
    def forward(self, x1, x2):
        return torch.ops.my_ops.add2(x1, x2)

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()   


def symbolic_add2(g, x1, x2):
    return g.op("ai.onnx.contrib::add2", x1, x2)
torch.onnx.register_custom_op_symbolic('my_ops::add2', symbolic_add2, 1)


# export
m = pool()
x1 = torch.randn([1, 1, 2, 2])
x2 = torch.rand([1, 1, 2, 2])
m.eval()
f = io.BytesIO()
output = m(x1, x2)
torch.onnx.export(
    m, (x1, x2), f,
    opset_version=12)
onnx_model = onnx.load(io.BytesIO(f.getvalue()))
print(output)

# import and run
from onnxruntime_extensions import onnx_op, PyOp, PyOrtFunction
@onnx_op(op_type='add2')
def add2(x1, x2):
    return torch.ops.my_ops.add2(x1, x2)

onnx_fn = PyOrtFunction.from_model(onnx_model)
out_ort = onnx_fn(x1.numpy(), x2.numpy())

np.testing.assert_allclose(to_numpy(output), out_ort[0], rtol=1e-03, atol=1e-05)
pass
```
But I got in from "out_ort = onnx_fn([x1.numpy(), x2.numpy()])":
[ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node:add2_0 : Node (add2_0) has input size 2 not in range [min=1, max=1]
It doesn't work to make a list or tuple of inputs (i.e.[x1, x2]). How can I run a multiple input model with custom operator? Any suggestion?

**Comment by wenbingl** [comment]
check this line https://github.com/microsoft/onnxruntime-extensions/blob/70aa18e14ec7e8cca317c8ae829de799da92de73/test/test_pyops.py#L113 for an example

**Comment by nkzyj** [comment]
Thanks a lot! It works.
