### ISSUE TITLE
Basic usage help needed

### ISSUE THREAD

**Issue by Robeast** [microsoft/onnxruntime-extensions#188]
Dear contributors,
please excuse me if my question is stupid - unfortunately I have not found the correct way of using the onnxruntime-extensions package for my use-case; I have not succeeded even after reading the examples in the doc, googling exhaustively and debugging into the package source code...

I would like to have a simple way of registering custom operators residing in ONNX graphs. First I create a really dummy onnx model with a custom node called `CUSTOM_ADD`

```python
import numpy as np
import onnx

B = 1
C = 3
H = 5
W = 5

# Inputs / outputs
i1 = onnx.helper.make_tensor_value_info('input1',  onnx.TensorProto.FLOAT, [B, C, H, W])
i2 = onnx.helper.make_tensor_value_info('input2',  onnx.TensorProto.FLOAT, [B, C, H, W])
o  = onnx.helper.make_tensor_value_info('output',  onnx.TensorProto.FLOAT, [B, C, H, W])

# Create a single Add node
nodes = [onnx.helper.make_node('Add', ['input1', 'input2'], ['output'])]

# Assemble graph, make model, infer shapes
graph_def = onnx.helper.make_graph(nodes, name="onnx-dummy", inputs=[i1, i2], outputs=[o])
model_def = onnx.helper.make_model(graph_def, producer_name="onnx-example")
model_def.opset_import[0].version = 11
model_def = onnx.shape_inference.infer_shapes(model_def)

# Replace Add with CUSTOM_ADD type
model_def.graph.node[0].op_type = 'CUSTOM_ADD'

# Save protobuf
onnx.save(model_def, "dummy.onnx")
```

Next, I try to register the behavior of the new node in onnx_extensions and infer the model. I define the behavior of the operation to add up the two inputs plus 6 in the `my_little_custom_add_implementation` function decorated by `onnx_op`.

```python
import numpy as np
from onnxruntime_extensions import onnx_op, PyOp, PyOrtFunction

# Register custom operator
@onnx_op(op_type="CUSTOM_ADD", inputs=[PyOp.dt_float, PyOp.dt_float])
def my_little_custom_add_implementation(x, y):
    return x + y + 6

# Load model
model_func = PyOrtFunction.from_model('dummy.onnx')

# Create input data
B = 1
C = 3
H = 5
W = 5

input1 = np.ones((B,C,H,W)).astype(np.float32)
input2 = np.ones((B,C,H,W)).astype(np.float32)

# Infer model
outputs = model_func([input1, input2])
```

I get the error at inference unfortunately saying:

```bash
onnxruntime.capi.onnxruntime_pybind11_state.InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Error in Node: : No Op registered for CUSTOM_ADD with domain_version of 11
```

So the registration of the new operator over Python obviously didn't work. 

Once again sorry for the beginner question... Could please anyone help me make this example work? I'd really appreciate it!

Thank you & Best regards,
RB

**Comment by wenbingl** [comment]
@Robeast,  you need to add 'ai.onnx.contrib' domain in into the ONNX Model.
check here for an example.
https://github.com/microsoft/onnxruntime-extensions/blob/a9737505ca5c762c1c6caa00fbc5aec2fae44cc2/test/test_math_ops.py#L11

**Comment by Robeast** [comment]
Oh wow. Thank you very much @wenbingl!!! This I could not have guessed... :) 

Maybe one more sidemark: I had issues even after fixing the domain - the ONNX IR version gave me troubles.

So maybe for others reading this thread, make sure that firstly your versioning matches following [this](https://github.com/microsoft/onnxruntime/blob/master/docs/Versioning.md) table. E.g.: using onnxruntime-extensions==0.4.2 and using onnxruntime==1.8.1 then you are limited to onnx<=1.9 and ONNX opset version<=14 and IR version <=7

The latter I had to enforce using `model_def.ir_version = 7` in the model generator script
