### ISSUE TITLE
Installation issue due to dependency

### ISSUE THREAD

**Issue by Fohlen** [microsoft/onnxruntime-extensions#189]
Hey there, on the M1 `onnxruntime-extensions` is currently uninstallable, even in the nightly. This is because `onnxruntime-extensions` requires `onnxruntime >= 1.6.0`. On the M1 however, we need to install `onnxruntime >= 1.9.0`. The solution here would be to loosen up the requirement to `> 1.6.0`.
I have verified that with `onnxruntime >= 1.9.0` it works on my M1 by installing the nightly from `test.pypi.org`
I'm curious as to why there is a requirement on the `onnxruntime` in the first place, as it should be interoptable.

**Comment by wenbingl** [comment]
@Fohlen
the reason is simple, the package test on M1 machine didn't fully pass and we don't have resource to fix it.  So, we postpone it until the next release.

BTW, is >= 1.6 looser than > 1.6?

**Comment by Fohlen** [comment]
Hey @wenbingl 
Currently the requirement is set to `~1.6` which translates to:
- `1.6` and any patch version

Loosening that up with `>=1.6` would solve the problem.
Is there anything we can do help and/or accelerate this issue?

**Comment by wenbingl** [comment]
where did you find "~= 1.6"?

In the requirements, it states >= 1.6
https://github.com/microsoft/onnxruntime-extensions/blob/a9737505ca5c762c1c6caa00fbc5aec2fae44cc2/requirements.txt#L3

**Comment by Fohlen** [comment]
Hey @wenbingl I believe you are right and this can be closed.
