### ISSUE TITLE
ONNXCompose error

### ISSUE THREAD

**Issue by uunal** [microsoft/onnxruntime-extensions#204]
Hello all, I've tried to test ONNXCompose with GPT2 model. I tried to compose model with preprocessor `PreHuggingfaceGPT2 `from module `pnp`. And I got an error which is:
`[InvalidGraph: [ONNXRuntimeError] : 10 : INVALID_GRAPH : This is an invalid model. Type Error: Type 'tensor(int64)' of input parameter (it_140322782567616) of operator (GPT2Tokenizer) in node (gpt2tokenizer_14) is invalid.]()`

I checked any problem may cause by opset, but all prepared using `opset=11`.  Is preprocessor for GPT2 functional or should I define a customOp for preprocessor?

Thanks a lot

**Comment by wenbingl** [comment]
The error means the input type is not matched.

Please hold on, the final version of the pre & post processing script authoring API is preliminary now, and it will be changed soon.

**Comment by uunal** [comment]
As I followed your updates, it looks like you improved many things. Is 'pre & post processing script authoring API' still in preliminary stage?
Thanks

**Comment by wenbingl** [comment]
@uunal , the latest composing API onnxruntime_extensions.pnp.export is under public test now. may you have a try and let me know the feedback?
