### ISSUE TITLE
Size of libortcustomops.so vs libortcustomops.dylib linux vs mac

### ISSUE THREAD

**Issue by github-lucas-plaetevoet** [microsoft/onnxruntime-extensions#219]
Hello,

I need to use the onnxruntime-extensions for a project that runs on a Linux machine. For testing purpose I have compiled the project on my mac using `./build.sh`. I get a dylib file whose size is 2.7 MB :`onnxruntime-extensions/out/Darwin/Release/libortcustomops.dylib` . I have used successfully this binary in my local application.

Now I want to compile it on the linux machine and I get a .so file that is now 48MB: `onnxruntime-extensions-main/out/Linux/Release/libortcustomops.so`

Any idea why there is such a difference between the two? Any idea on how I could reduce it?

Apart from the compiler that is different (GNU 8.3.0 for linux vs AppleClang 12.0.5.12050022), could something else explain the diff?

Thanks

**Comment by wenbingl** [comment]
In Linux SO file compiled with default arguments, it contains a lot of debugging information, you may strip them by some command line like the following 
__strip --strip-all ./libortcustomops.so_

BTW, if you knew what operators are needed for your application, you can turn off the other operators to make the library binary even smaller.

it would be something like ./build.sh -DOCOS_ENABLE_BLINGFIRE=OFF ...

**Comment by github-lucas-plaetevoet** [comment]
Thanks a lot, the strip command did the trick and reduced drastically the size!!
