### ISSUE TITLE
Building crashes vm instance

### ISSUE THREAD

**Issue by uunal** [microsoft/onnxruntime-extensions#232]
Hello, 

I've been trying to install new changes at the repository. I've used building with  Python dependency. Installation crashes the vm instance. All gcc and cmake libraries are up to date. I could not discover what causes the problem.
In earlier version, I followed the same instructions and succesfully able to install. 

Any suggestions or did you come up such problem?

**Instance Info:**
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

**Comment by wenbingl** [comment]
Can you share some error message here?
If you didn't see anything in the screen on building, normally it's out of memory, probably you should assign more memory >8G for compiling, or you disable OPENCV compiling which takes a lot of memory consumption.

**Comment by uunal** [comment]
I've tried your suggestion with disabling OPENCV compiling. It solved the issue. 
Memory consumption is the problem at the vm instance.

Thank you!
