### ISSUE TITLE
[C# Windows] Standardize the name of ortcustomops.dll

### ISSUE THREAD

**Issue by GeorgeS2019** [microsoft/onnxruntime-extensions#239]
Currently it seems much of the code of [ortcustomops.cc](https://github.com/microsoft/onnxruntime-extensions/pull/234/files#diff-91efe40c842a68236952341ac4cc09447bb3c0c61cf64df53a15a63acc5c41d2) is related to based on the discussion [here](https://github.com/microsoft/onnxruntime-extensions/pull/234/files)

Is it possible to make both FILES **ortcustomops.cc** AND [**custom_op_library.cc**](https://github.com/microsoft/onnxruntime/blob/master/onnxruntime/test/testdata/custom_op_library/custom_op_library.cc) having the same NAME?

In this way it should be possible take ortcustomops.dll created here usable using e.g. [c# unit test here](https://github.com/microsoft/onnxruntime/blob/ce4ac6d3280f61b8c30801d044f32d423f69559c/csharp/test/Microsoft.ML.OnnxRuntime.Tests.NetCoreApp/InferenceTest.netcore.cs#L613)

**Comment by GeorgeS2019** [comment]
Both files are very different. Could both be made same?

![image](https://user-images.githubusercontent.com/49812372/171851858-d79b5153-ed74-4cec-8aba-3805a18099bf.png)

**Comment by GeorgeS2019** [comment]
is #include "onnxruntime_extensions.h" from onnxruntime-extension being used in onnxrntime project?

**Comment by GeorgeS2019** [comment]
#### onnxruntime_extensions.h
```c++
// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License.

#pragma once
#include "onnxruntime_c_api.h"

#ifdef __cplusplus
extern "C" {
#endif

OrtStatus* ORT_API_CALL RegisterCustomOps(OrtSessionOptions* options, const OrtApiBase* api);

#ifdef __cplusplus
}
#endif
```

**Comment by GeorgeS2019** [comment]
Question how "onnxruntime_c_api.h" from onnxruntime-extension and "onnxruntime_cxx_api.h" from onnxruntime similar and different?

**Comment by GeorgeS2019** [comment]
Relevant discussion: [NER transformers model packed in one onnx file with Sentencepiece Tokenizer](https://github.com/microsoft/onnxruntime-extensions/issues/164)

**Comment by snnn** [comment]
onnxruntime has release tags. If you copy onnxruntime_c_api.h from one release tag, then keep it private and use it with a newer version of onnxruntime, it would be fine.  So I guess the authors of this repo copied the file in such a way, and did a few small modifications. You can diff the two files to see differences.
