### ISSUE TITLE
Cannot add input and output names to model with BertTokenizer

### ISSUE THREAD

**Issue by natke** [microsoft/onnxruntime-extensions#243]
When specifying input_names and output_names to pnp.export, they are not added to the graph.

Augment model code is:

```
augmented_model = pnp.export(augmented_model,
                             test_question,
                             opset_version=12,
                             input_names=['question'],
                             output_names=['start', 'end'],
                             output_path=model_name + '-aug.onnx',
                             dynamic_axes={'question': [0]})
```

Source here: https://github.com/natke/onnxruntime-inference-examples/blob/dataproc-nlp-mobile/mobile/examples/question_answering/model/augment_model.py

Graph inputs and outputs:

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/3302433/172221809-dfdddc12-b090-4967-b4bd-b249c67191b6.png)
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/3302433/172221833-9647913c-f1ba-4810-a3db-d86b3db88e3d.png)

**Comment by shaahji** [comment]
Fixed by #263
