### ISSUE TITLE
[COMPLIANCE] Run VC++ Static Code Analyzer

### ISSUE THREAD

**Issue by snnn** [microsoft/onnxruntime-extensions#246]
Copy the https://github.com/microsoft/onnxruntime/blob/master/cmake/Sdl.ruleset from the main ORT repo to this repo, and run Run VC++ Static Code Analyzer with this ruleset. The xml file is based on the minimal required SDL ruleset. Feel free to enable more rules. 

@snnn will setup this pipeline. The dev team of this repo will fix the warnings. 

For now we don't setup such things for clang. We will do it when we publish iOS packages.

**Comment by natke** [comment]
Done
