### ISSUE TITLE
Invalid Argument Problem

### ISSUE THREAD

**Issue by uunal** [microsoft/onnxruntime-extensions#258]
In example, _gpt2bs.py_, with or without enabling custom tokenizer op, the error below is occurred:
`[ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Unexpected input data type. Actual: (tensor(int64)) , expected: (tensor(int32))`

I've tried to chage dtype in `_extract_endict` function, but nothing changes at the output (with enable_tokenizers=false). In the states, input_ids returns tensor(int64).

Where should I control input dtype?
Thanks

**Comment by wenbingl** [comment]
did you also change attentions_mask, which is int32.

BTW, the script is deprecated now, you can check more info at the header lines in this file.

**Comment by uunal** [comment]
Thanks, I will try latest contrib op solution and will write the feedback.

**Comment by uunal** [comment]
I tried your suggestion and I want to combine model,tokenizer and custom ops as how pnp works at example. That solution is not what I need to test. I do not have a problem on coverting model(only) to onnx. 

Maybe I can show the `states[1:]` which is used with `pyfunc_from_model(gpt2_core)`. The problem above starts there:

`[name: input_ids, tensor([[  47, 7487]], dtype=torch.int32), dtype=torch.int32, name: v0_73, tensor([[0, 1]]), dtype=torch.int64, name: attention_mask, tensor([[1., 1.]]), dtype=torch.float32, name: v0_114, tensor([[0]]), dtype=torch.int64, name: vcos_118, tensor([[0.]]), dtype=torch.float32, name: vcos_122, tensor([[True]]), dtype=torch.bool, name: v0_129, tensor([[  47, 7487]], dtype=torch.int32), dtype=torch.int32, name: vcos_126, tensor([[0.]]), dtype=torch.float32, name: v0_79, tensor([], size=(2, 1, 12, 0, 64)), dtype=torch.float32, name: v0_85, tensor([], size=(2, 1, 12, 0, 64)), dtype=torch.float32, name: v0_91, tensor([], size=(2, 1, 12, 0, 64)), dtype=torch.float32, name: v0_97, tensor([], size=(2, 1, 12, 0, 64)), dtype=torch.float32, name: v0_103, tensor([], size=(2, 1, 12, 0, 64)), dtype=torch.float32, name: v0_109, tensor([], size=(2, 1, 12, 0, 64)), dtype=torch.float32]`

How to fix dtypes in that? Or can you lead me another way to test full model dump?
