### ISSUE TITLE
No wheel for the M1

### ISSUE THREAD

**Issue by Fohlen** [microsoft/onnxruntime-extensions#276]
Dear ONNX team, currently it's possible to build this wheel from source on the M1, but there is no official M1 / ARM64 wheel on pypi, which makes it impossible to install this.

**Comment by wenbingl** [comment]
Yes, that's planned.
Stay tuned.

**Comment by Fohlen** [comment]
Hey @wenbingl, thanks for letting me know.. is there anything that could be done on our side to accelerate this? Adding a PR to the pipeline? Best

**Comment by wenbingl** [comment]
released, https://pypi.org/project/onnxruntime-extensions/#files
