### ISSUE TITLE
C++ input tensor with string not working.

### ISSUE THREAD

**Issue by ns-wxin** [microsoft/onnxruntime-extensions#303]
Hi, 

It's really hard to find any examples online to get string as input tensor with Onnx Runtime. I saw some example here:

https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/test/shared_lib/test_inference.cc

at Line 490, it's calling session_options.EnableOrtCustomOps(); But when I tested it. I got 

`terminate called after throwing an instance of 'Ort::Exception'
  what():  EnableOrtCustomOps: Custom operators in onnxruntime-extensions are not enabled
Aborted (core dumped)`

But if I add 

`    void* handle = nullptr;
    Ort::ThrowOnError(Ort::GetApi().RegisterCustomOpsLibrary((OrtSessionOptions*)m_sessionOptions.get(), "libortextensions.so", &handle));
    std::cout << "Registered custom ops lib...\n";`

I got "segmentation fault". I'm linking to 1.12.1 onnxruntime library. Really would appreciate if someone has working example on how to create input tensor with string. Here's my code. The problem is in session creation.

Here's the code, somehow the format didn't turn out to be all in code style:

`
#include <iostream>
#include <fstream>
#include <streambuf>
#include "TextMLFingerprintGenerator.h"

std::string readTextFileToBuffer(std::string filename) {
    std::ifstream t(filename);
    std::string buffer((std::istreambuf_iterator<char>(t)),
                        std::istreambuf_iterator<char>());
    return buffer;
}

void run() {
    std::string modelFile = "/home/wxin/Wayne/fingerprinting/fingerprinting_embedder.onnx";
    int threadNum = 1;
    std::string txtFile = "/tmp/test.txt";
    std::cout << "constructing generator...with " << modelFile << std::endl;
    std::cout << "Loading model: " << modelFile << std::endl;
    Ort::Env m_env (OrtLoggingLevel::ORT_LOGGING_LEVEL_INFO, "textML Encoder");
    Ort::SessionOptions m_sessionOptions;
    m_sessionOptions.SetIntraOpNumThreads(threadNum);
    m_sessionOptions.SetGraphOptimizationLevel( GraphOptimizationLevel::ORT_ENABLE_ALL);
    m_sessionOptions.DisableCpuMemArena();
    std::cout << "Starting session...\n";
    void* handle = nullptr;
    Ort::ThrowOnError(Ort::GetApi().RegisterCustomOpsLibrary((OrtSessionOptions*)&m_sessionOptions, "libortextensions.so", &handle));
    std::cout << "Registered custom ops lib...\n";
    m_sessionOptions.EnableOrtCustomOps();
    Ort::Session session (m_env, modelFile.c_str(), m_sessionOptions);

    std::cout << "Loaded model: " << modelFile << std::endl;

    // fingerprint::printVector(*embeddings);
}

int main(int argc, const char * argv[]) {
  run();
  return 0;
}
`

**Comment by ns-wxin** [comment]
The string input tensor code is as following, but I didn't get to this point because session wasn't able to create.

`    const char* inputText[1] = {buffer.c_str()};
    std::vector<int64_t> input_dims = {1, 1};
    std::chrono::high_resolution_clock::time_point t_start, t_end, t2_start;

    std::shared_ptr<std::vector<float>> outputTensorValues = std::make_shared<std::vector<float>>(OutputTensorSize);
    std::vector<Ort::Value> inputTensors;
    std::vector<Ort::Value> outputTensors;
    std::vector<const char*> inputNames{m_inputName};
    std::vector<const char*> outputNames{m_outputName};

    Ort::Value text_tensor = Ort::Value::CreateTensor(m_allocator, input_dims.data(), input_dims.size(), ONNX_TENSOR_ELEMENT_DATA_TYPE_STRING);
    auto result = Ort::GetApi().FillStringTensor(static_cast<OrtValue*>(text_tensor), inputText, 1U);
    std::cout << "convert result " << result << std::endl;
    inputTensors.push_back(std::move(text_tensor));
    outputTensors.push_back(Ort::Value::CreateTensor<float>(
                  m_memoryInfo, outputTensorValues->data(), OutputTensorSize,
                  m_outputDims.data(), m_outputDims.size()));

    m_modelSession->Run(Ort::RunOptions{nullptr}, inputNames.data(),
          inputTensors.data(), 1, outputNames.data(),
          outputTensors.data(), 1);

    std::cout << outputTensorValues << std::endl;
`

**Comment by wenbingl** [comment]
EnableOrtCustomOps requires the onnxruntime library was built from source with some additional parameters:
https://github.com/microsoft/onnxruntime-extensions#the-static-library-and-link-with-onnxruntime

And you check build the ort-extensions as a shared library, and the C++ string example can be found here:

https://github.com/microsoft/onnxruntime-extensions/blob/4189db8129f30eb0511881532d747af71d655021/test/shared_test/test_ortops_strings.cc#L497

BTW, can you share more details about how ort-extensions was built?

**Comment by ns-wxin** [comment]
I'll give a try on building onnxruntime with additional parameters.

I built ort-extensions by doing the following:

1. git clone <source>
2. mkdir build; cd build
3. cmake -DOCOS_ENABLE_OPENCV_CODECS=OFF -DOCOS_ENABLE_OPENCV=OFF -DCMAKE_PREFIX_PATH=/opt/3p ..
4. make -j4

I had to turn off OPENCV stuff because the build failed.

**Comment by wenbingl** [comment]
Are you able to edit this line https://github.com/microsoft/onnxruntime/blob/72076b1eb27490a8ac64ea8c1743de7449addaf1/cmake/CMakeLists.txt#L1314 to relieve the constraint?

**Comment by ns-wxin** [comment]
Thanks @wenbingl for the help. I'm able to build onnxruntime with extensions and the shared lib works. I'm closing this ticket.

**Comment by ns-wxin** [comment]
I was able to do a regular build with "-Werror" removed in the CMakeList.txt.

Now that I'm getting MSAN build error and looks like the complaints are standard C++ lib routines. I need advice on getting MSAN built with onnxruntime+extensions.

`
[ 80%] Building CXX object CMakeFiles/onnxruntime_test_all.dir/home/wxin/toolchain_build/onnxruntime/onnxruntime/test/common/logging/sinks_test.cc.o
/usr/bin/ld: libonnxruntime_session.a(onnxruntime_c_api.cc.o): in function `OrtApis::CreateEnvWithCustomLogger(void (*)(void*, OrtLoggingLevel, char const*, char const*, char const*, char const*), void*, OrtLoggingLevel, char const*, OrtEnv**)':
onnxruntime_c_api.cc:(.text._ZN7OrtApis25CreateEnvWithCustomLoggerEPFvPv15OrtLoggingLevelPKcS3_S3_S3_ES0_S1_S3_PP6OrtEnv+0x21): undefined reference to `__msan_param_tls'
/usr/bin/ld: onnxruntime_c_api.cc:(.text._ZN7OrtApis25CreateEnvWithCustomLoggerEPFvPv15OrtLoggingLevelPKcS3_S3_S3_ES0_S1_S3_PP6OrtEnv+0xc2): undefined reference to `__msan_retval_tls'
`

and 

`
/usr/bin/ld: _deps/blingfire-build/libbingfirtinydll_static.a(blingfiretokdll.cpp.o): in function `TextToSentencesWithOffsetsWithModel':
blingfiretokdll.cpp:(.text.TextToSentencesWithOffsetsWithModel+0x324): undefined reference to `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream()'
/usr/bin/ld: blingfiretokdll.cpp:(.text.TextToSentencesWithOffsetsWithModel+0x388): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
/usr/bin/ld: blingfiretokdll.cpp:(.text.TextToSentencesWithOffsetsWithModel+0x55e): undefined reference to `std::basic_ostream<char, std::char_traits<char> >& std::__ostream_insert<char, std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char> >&, char const*, long)'
`

Looks like the subcomponent "blingfire" was pulled during the build of the overall extensions. Is there a way I can tweak to make it "MSAN" compatible?

Also is it possible to disable "onnxruntime_test_all" for MSAN build?

**Comment by ns-wxin** [comment]
closing this and opening a new one for MSAN build error.
