### ISSUE TITLE
ClipTokenizer error on Android

### ISSUE THREAD

**Issue by slavabarkov** [microsoft/onnxruntime-extensions#374]
Greetings!

Loading a model with CLIPTokenizer on Android, using the latest release: 
```
implementation 'com.microsoft.onnxruntime:onnxruntime-extensions-android:0.7.0'
```
and initializing the session like in SuperResolution example code:
```
val sessionOptions: OrtSession.SessionOptions = OrtSession.SessionOptions()
sessionOptions.registerCustomOpLibrary(OrtxPackage.getLibraryPath())
val session = ortEnv.createSession(model, sessionOptions)
```
throws an error:
```
Caused by: ai.onnxruntime.OrtException: Error code - ORT_FAIL - message: Fatal error: ai.onnx.contrib:CLIPTokenizer(-1) is not a registered function/op
```
Loading the same model with Python package built from rel-0.7 with similar initialization works fine:
```
so = ort.SessionOptions()
so.register_custom_ops_library(get_library_path())
sess = ort.InferenceSession(model.SerializeToString(), so)
```
What could be the cause of this error?

**Comment by wenbingl** [comment]
The current android package only contains a few of operators for the sake of the package size. Can you build the package from source by yourself? 

https://github.com/microsoft/onnxruntime-extensions/blob/main/docs/development.md

**Comment by slavabarkov** [comment]
Thank you for the answer! I will try building the package from source.
