### ISSUE TITLE
Adding custom operators in onnxruntime

### ISSUE THREAD

**Issue by HemaSowjanyaMamidi** [microsoft/onnxruntime-extensions#43]
How to add custom operators using ort-customops(framework independent)?
I successfully added the operator in onnx. So for the model to be compiled using the runtime it should be added in runtime as well. Need help in this area. Thanks.

**Comment by wenbingl** [comment]
From the name itself, "onnxruntime customops". this library cannot be framework independent.

**Comment by xadupre** [comment]
What operator do you have in mind? You can look into PR #24 as an example.

**Comment by HemaSowjanyaMamidi** [comment]
@xadupre I just want to test adding a new operator to ort nothing in specific. Can add any operator which even involves computation?

**Comment by xadupre** [comment]
If you just want to try, you can just create a PR. I usually create two versions of the same operator, one in python, one in C++ to compare the outputs. I recommend starting with python. The current main branch only run CI on Windows, #44 does it for Linux, MacOS, Windows and has a more consistent behaviour when it comes to strings. It should be merged in a couple of days.

**Comment by GeorgeS2019** [comment]
The[ feature request here](https://github.com/microsoft/onnxruntime/issues/11657) could include the discussion here.
