### ISSUE TITLE
Question: Is it possible to create a custom operator with multiple input types ?

### ISSUE THREAD

**Issue by Johansmm** [microsoft/onnxruntime-extensions#451]
I want to know if it is possible to create an operator that receives two possible input types, something like : 
```python
import numpy
from onnxruntime_extensions import PyOp, onnx_op

@onnx_op(op_type="Inverse", inputs=[[PyOp.dt_float, PyOp.dt_double]], outputs=[[PyOp.dt_float, PyOp.dt_double]])
def inverse(x):
    return numpy.linalg.inv(x).astype(x.dtype)
```

If the answer is no, what should be the correct way to handle a single type of operation with the same `op_type`, since registering an operation with the same `op_type` name throws an error:

```python
import numpy
from onnxruntime_extensions import PyOp, onnx_op

@onnx_op(op_type="Inverse", inputs=[PyOp.dt_float], outputs=[PyOp.dt_float])
def inverse_float(x):
    return numpy.linalg.inv(x)

@onnx_op(op_type="Inverse", inputs=[PyOp.dt_double], outputs=[PyOp.dt_double])
def inverse_double(x):
    return numpy.linalg.inv(x)
```

**Comment by wenbingl** [comment]
@Johansmm, in near team, the only way to do that is create two ops for different data types. like "Inverse", "Inverse_f64"

**Comment by RandySheriffH** [comment]
We have enhanced ort custom op logics to support this:
https://github.com/microsoft/onnxruntime/pull/15184
Basically, there you could register several kernels of different input types for the same op.

**Comment by wenbingl** [comment]
Thanks for  Randy's solution.
@Johansmm, So if you upgrade your onnxruntime to latest 1.15, which was just published, the second code snippets you post should work now.

**Comment by Johansmm** [comment]
Thanks @RandySheriffH and @wenbingl for your comments. I tried that with the following code, however I have a segmentation fault error. 

```python
import numpy

from onnx import TensorProto as TP
from onnx.helper import make_model, make_node, make_graph, make_tensor_value_info
from onnxruntime import InferenceSession, SessionOptions
from onnxruntime_extensions import PyOp, onnx_op, get_library_path

# Define custom ops
@onnx_op(op_type="Inverse", inputs=[PyOp.dt_float], outputs=[PyOp.dt_float])
def inverse_float(x):
    return numpy.linalg.inv(x)

@onnx_op(op_type="Inverse", inputs=[PyOp.dt_double], outputs=[PyOp.dt_double])
def inverse_double(x):
    return numpy.linalg.inv(x)

# Define a graph with custom op
X = make_tensor_value_info('X', TP.FLOAT, [None, None])
Y = make_tensor_value_info('Y', TP.FLOAT, [None, None])
nodes = [make_node('Inverse', ['X'], ['Y'], domain='ai.onnx.contrib')]
graph = make_graph(nodes, "inverse", [X], [Y])
onnx_model = make_model(graph)

# Define session
so = SessionOptions()
so.register_custom_ops_library(get_library_path())
model = InferenceSession(onnx_model.SerializeToString(), so, providers=['CPUExecutionProvider'])
# segmentation fault at this point
``` 

Any idea ?

System information
ONNX version (1.14.0 or 1.13.0)
Python version (3.8.10)
Protobuf version (3.20.3)

**Comment by wenbingl** [comment]
I can repro the issue with official ort and ort-extensions packages as well. It crashed in native code with a null pointer, it needs some time to fix it.

**Comment by RandySheriffH** [comment]
Trying out with the script - do any of you have a stack trace btw?
@Johansmm
@wenbingl

**Comment by RandySheriffH** [comment]
@Johansmm: 1.15.0 indeed has the problem, but the latest main build from the source is fine, mind give it a try?

```
build.bat --config RelWithDebInfo --build_wheel --parallel --skip_tests
```

**Comment by Johansmm** [comment]
@RandySheriffH, building the latest `onnxruntime` version (1.16.0) this solution works. Thank you very much for your help !
