### ISSUE TITLE
Tensor issue  best.with_pre_post_processing.onnx Issue 

### ISSUE THREAD

**Issue by alpha-31** [microsoft/onnxruntime-extensions#480]
I am getting this error although my model work well in onnx form and in .pt form.
 
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Split node. Name:'post_process_14' Status Message: C:\a\_work\1\s\onnxruntime\core\framework\op_kernel.cc:83 
onnxruntime::OpKernelContext::OutputMLValue status.IsOK() was false. Tensor shape cannot contain any negative value

**Comment by wenbingl** [comment]
Need more info to understand what happens, what's the model?

**Comment by alpha-31** [comment]
Yeah i using Yolov8 with pretrained weights. 
The issue is resolved. But the main things i want to add pre and post preocessing to the model.
Now it is also done, the main thing is that i have one pre-post-processed yolov8 pretrained weights whichgives me graph on the netron where the bounding boxes are separate but when i convert using the ort-extentions tool of yolo_e2e but i did not get any kind of weights separately.
![image](https://github.com/microsoft/onnxruntime-extensions/assets/60798854/8699e906-ab37-4f3a-8a87-dc372b5d01e5)
![image](https://github.com/microsoft/onnxruntime-extensions/assets/60798854/1ed61335-c1e1-4c35-a126-d685aa9fda20)

**Comment by wenbingl** [comment]
@wejoncy, can you answer alpha-31's question here?

**Comment by wejoncy** [comment]
@alpha-31 Do you mean the separate output "scaled_box_out_next"? You just need to add a `Debug(),` at this line https://github.com/microsoft/onnxruntime-extensions/blob/981cb049ff956a1c99ab178b36ffc83664a678f2/onnxruntime_extensions/tools/add_pre_post_processing_to_model.py#L270
and run the extension_tools again.

**Comment by alpha-31** [comment]
> @wejoncy, can you answer alpha-31's question here?

Yeah i would love to hear from you..

**Comment by alpha-31** [comment]
> @alpha-31 Do you mean the separate output "scaled_box_out_next"? You just need to add a `Debug(),` on top of this line
> 
> https://github.com/microsoft/onnxruntime-extensions/blob/981cb049ff956a1c99ab178b36ffc83664a678f2/onnxruntime_extensions/tools/add_pre_post_processing_to_model.py#L270
> 
> 
> and run the extension_tools again.

yeah exactly i want those also but here is the netron visualize for the model i am have in the demo app
![image](https://github.com/microsoft/onnxruntime-extensions/assets/60798854/578d6d1c-90be-4404-b8e8-6dd91e7406f4)


But my model has this one 
![image](https://github.com/microsoft/onnxruntime-extensions/assets/60798854/49f8d5db-712c-473b-9f76-5e9ac4dd490b)

Would that debug do the thing ?

**Comment by alpha-31** [comment]
@wejoncy , But one thing more i want like the image with the drawing boxes and the boxes separately just like the above the defualt yolov8n-pre-post-processed.

**Comment by alpha-31** [comment]
@wejoncy @wenbingl Thanks alot i got it Thanks alot

**Comment by iamxiaojuan** [comment]
@wejoncy After I added **Debug(),** like you said, it didn't output "**scaled_box_out_next**". As shown in the figure:

![Image](https://github.com/user-attachments/assets/faa9a6d8-a285-4f8c-bcaf-3874c02fbfd0)
（The code version is main）


The figure shows my changes to "add_pre_post_processing_to_model"：

![Image](https://github.com/user-attachments/assets/2bbaa06c-0ada-435f-80dc-f8c5a0c82264)
