### ISSUE TITLE
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolo_models/yolov5s_int8.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46

### ISSUE THREAD

**Issue by akshay9396** [microsoft/onnxruntime-extensions#517]
Describe the bug
I am trying to quantize yolov5s (from ultralytic's [repo)](https://github.com/ultralytics/yolov5/blob/master/tutorial.ipynb) model using ONNXRuntime quantization. Quantization runs succesfully. However, when validating the quantized model using Ultralytics val.py, I am getting obove error. (FP32 ONNX model gives correct results).

Traceback (most recent call last):
  File "val.py", line 381, in <module>
    main(opt)
  File "val.py", line 354, in main
    run(**vars(opt))
  File "/mnt/c/users/u28z48/dsvenv/myvenv/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "val.py", line 138, in run
    model = DetectMultiBackend(weights, device=device, dnn=dnn, data=data)
  File "/mnt/c/Users/u28z48/yolov5/yolov5/models/common.py", line 329, in __init__
    session = onnxruntime.InferenceSession(w, providers=providers)
  File "/mnt/c/users/u28z48/dsvenv/myvenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 360, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "/mnt/c/users/u28z48/dsvenv/myvenv/lib/python3.8/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 397, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from yolo_models/yolov5s_int8.onnx failed:/onnxruntime_src/onnxruntime/core/graph/model_load_utils.h:46 void onnxruntime::model_load_utils::ValidateOpsetForDomain(const std::unordered_map<std::basic_string<char>, int>&, const onnxruntime::logging::Logger&, bool, const string&, int) ONNX Runtime only *guarantees* support for models stamped with official released onnx opset versions. Opset 19 is under development and support for this is limited. The operator schemas and or other functionality may change before next ONNX release and in this case ONNX Runtime will not guarantee backward compatibility. Current official support for domain com.ms.internal.nhwc is till opset 18.

Urgency
Need to know whether this is a limitation of ORT or if I am doing something wrong ASAP

Let me know anything is needed form myside.

**Comment by wenbingl** [comment]
why does this issue related to this REPO?
For you issue, you can specify opset_version=18 on exporting onnx model as the error message suggested.
