### ISSUE TITLE
StringLength does not match expected type (tensor(int64))

### ISSUE THREAD

**Issue by MaximeChurin** [microsoft/onnxruntime-extensions#550]
Hello,
I used [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx) to transform my TF model to ONNX with `--opset 18 --extra_opset ai.onnx.contrib:1 --custom-ops StringJoin:ai.onnx.contrib,StringLength:ai.onnx.contrib`.
When loading it with `onnxruntime` and the associated custom ops  (see snippet below) I have the following error `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Load model from model.onnx failed:Type Error: Type (tensor(int32)) of output arg (StatefulPartitionedCall/StringLength:0) of node (StatefulPartitionedCall/StringLength) does not match expected type (tensor(int64)).`
```python
import onnxruntime as rt
from onnxruntime_extensions import get_library_path

sess_options = rt.SessionOptions()
sess_options.register_custom_ops_library(get_library_path())
inference_session = rt.InferenceSession("path", sess_options, providers=["CPUExecutionProvider"])
```

I solved it by forking [onnxruntime-extensions](https://github.com/microsoft/onnxruntime-extensions) and [updating the string length operator to int32](https://github.com/MaximeChurin/onnxruntime-extensions/commit/16aea8b6c544e133b9b434cfcb106ef968e84bf9) similar to the output of [tensorflow op](https://www.tensorflow.org/api_docs/python/tf/strings/length)

What should be the source of truth and do you have a workaround to avoid a fork?

**Comment by wenbingl** [comment]
May you add a ONNX Cast Operator after StringLength node in the model graph?
https://github.com/onnx/onnx/blob/main/docs/Operators.md#Cast

**Comment by MaximeChurin** [comment]
I tried to wrap it within a tf.cast op in my initial code but after conversion as soon as it goes within StringLength it fails and the `InferenceSession` is not created. I might have done something wrong but could not make it work

**Comment by MaximeChurin** [comment]
Thanks I added a cast directly in onnx after tf2onnx conversion and it works (I also needed to change the value_info for the StringLength node)
