### ISSUE TITLE
StringJoin issue on CUDA EP: scalar input could only be applied to CPU tensor

### ISSUE THREAD

**Issue by MaximeChurin** [microsoft/onnxruntime-extensions#577]
Hello,
I used [tensorflow-onnx](https://github.com/onnx/tensorflow-onnx) to transform my TF model to ONNX with either `--opset 18 --extra_opset ai.onnx.contrib:1 --custom-ops StringJoin:ai.onnx.contrib` or `--opset 18 --extra_opset ai.onnx.contrib:1` or `--opset 18 --extra_opset ai.onnx.contrib:1 --custom-ops StringJoin:ai.onnx.contrib,StringSplit:ai.onnx.contrib`

When loading it with `onnxruntime` and the associated custom ops (aka CPU EP) everything works. With `onnxruntime-gpu` and the associated custom ops (see snippet below, same problem using io_binding) I have the following error `2023-10-18 10:53:42.171526398 [E:onnxruntime:, sequential_executor.cc:514 ExecuteKernel] Non-zero status code returned while running StringJoin node. Name:'StatefulPartitionedCall/ReduceJoin/ReduceJoin' Status Message: 1: scalar input could only be applied to CPU tensor`

```python
import onnxruntime as rt
from onnxruntime_extensions import get_library_path
import numpy as np

sess_options = rt.SessionOptions()
sess_options.register_custom_ops_library(get_library_path())
inference_session = rt.InferenceSession("path", sess_options, providers=["CUDAExecutionProvider"])
inputs = np.random.randint(0, 249, (64, 45), dtype=np.int32)
inference_session.run(None, {"inputs": inputs})
```

How can I use this operation with CUDA EP like other operations that are placed on CPU EP? I attached a minimal onnx model with the problematic operations
[model.zip](https://github.com/microsoft/onnxruntime-extensions/files/13021363/model.zip)

**Comment by wenbingl** [comment]
It looks like the issue doesn't occur in the StringJoin kernel, while it happens on KernelExecutor in ORT. So I think moving this issue to ORT github may get some help more quickly.

**Comment by MaximeChurin** [comment]
Thanks I move it there

**Comment by MaximeChurin** [comment]
@wenbingl can you tag somebody relevant on the ORT [issue](https://github.com/microsoft/onnxruntime/issues/18018)?

**Comment by wenbingl** [comment]
> @wenbingl can you tag somebody relevant on the ORT [issue](https://github.com/microsoft/onnxruntime/issues/18018)?

I believe there is a system to forward the issue to a corresponding team alias, please stay tuned.
