### ISSUE TITLE
Likely a typo

### ISSUE THREAD

**Issue by axelfurlan** [microsoft/onnxruntime-extensions#584]
https://github.com/microsoft/onnxruntime-extensions/blob/646962072d397b87e1b48b87d3a92b8c3d3fa1ad/onnxruntime_extensions/tools/add_pre_post_processing_to_model.py#L289

Shouldn't this be `new_model` instead of `new_mode`?

**Comment by skottmckay** [comment]
It actually shouldn't, but the name should be clearer and there could be a comment clarifying what we're doing.

We want to run the shape inferencing to validate the model (could add `strict=True`) but do not want to save that model as it will be unnecessarily large with all the shape information (which obviously can be inferred).

**Comment by axelfurlan** [comment]
Fixed in https://github.com/microsoft/onnxruntime-extensions/pull/595

**Comment by axelfurlan** [comment]
Fixed in https://github.com/microsoft/onnxruntime-extensions/pull/595
