### ISSUE TITLE
"com.microsoft.onnxruntime_extensions" is not a valid bundle identifier

### ISSUE THREAD

**Issue by ronyfadel** [microsoft/onnxruntime-extensions#825]
the exported framework has a bundle identifier of "com.microsoft.onnxruntime_extensions", which is invalid (because of the "_") and Xcode is starting to reject it.

**Comment by wenbingl** [comment]
@edgchen1 , any suggestions?

**Comment by edgchen1** [comment]
> [@edgchen1](https://github.com/edgchen1) , any suggestions?

maybe rename it to "com.microsoft.onnxruntime-extensions".

https://developer.apple.com/documentation/bundleresources/information_property_list/cfbundleidentifier?language=objc

**Comment by ronyfadel** [comment]
https://github.com/microsoft/onnxruntime-extensions/pull/829

**Comment by ronyfadel** [comment]
@edgchen1 @wenbingl can we create a new release please, both here and in https://github.com/microsoft/onnxruntime-swift-package-manager ?

The issues will start piling up soon as this breaks the package in Xcode 16.0

**Comment by wenbingl** [comment]
@apsonawane, can you cherry-pick PR https://github.com/microsoft/onnxruntime-extensions/pull/829 to the release branch, which is minor change but fixed a very important issue?

**Comment by ronyfadel** [comment]
Hey @apsonawane, @wenbingl , any updates to this?

The way I see it we'll need a new release in this project, and a new one at https://github.com/microsoft/onnxruntime-swift-package-manager that references it.

**Comment by apsonawane** [comment]
Hello @ronyfadel, we are planning on releasing this week will keep you updated.

Thank you!

**Comment by ronyfadel** [comment]
@apsonawane any updates??

**Comment by edgchen1** [comment]
0.13.0 was released. The tag was recently created.
https://github.com/microsoft/onnxruntime-extensions/releases/tag/v0.13.0
