### ISSUE TITLE
PythonOp doesn't support attribute

### ISSUE THREAD

**Issue by wenbingl** [microsoft/onnxruntime-extensions#9]

**Comment by Toudsour** [comment]
Can we add a C API to get constant input from OrtKernelInfo, maybe some depend on those constant inputs for initialization.

**Comment by xadupre** [comment]
The only way to do this today is to add a node Constant (https://github.com/onnx/onnx/blob/master/docs/Operators.md#Constant) in the ONNX graph and to send the value to the node as an input.

**Comment by Toudsour** [comment]
We can get attribute via the following API:
```c++
struct CustomOpApi {
  CustomOpApi(const OrtApi& api) : api_(api) {}

  template <typename T>  // T is only implemented for float, int64_t, and string
  T KernelInfoGetAttribute(_In_ const OrtKernelInfo* info, _In_ const char* name);
...
}
```

I have verified in my PR #48

**Comment by xadupre** [comment]
Thanks for doing that. I think there is still a few supported types: int64, float, string. No support for arrays.
